import { MetadataProps, getAllPosts, getPostsForTopPage } from '@/lib/notionAPI'
import Head from 'next/head'
import { SinglePost } from '@/components/Post/SinglePost'
import { GetStaticPaths, GetStaticProps } from 'next/types'

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [{ params: { page: '1' } }, { params: { page: '2' } }],
    fallback: 'blocking',
  }
}

export const getStaticProps: GetStaticProps = async () => {
  const fourPosts: MetadataProps[] = await getPostsForTopPage()
  return {
    props: { fourPosts },
    revalidate: 60, // 60秒ごと更新する(ISR)
  }
}
type Props = {
  fourPosts: MetadataProps[]
}

const BlogPageList = ({ fourPosts }: Props) => {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          Notion Blog🚀
        </h1>
      </main>
      <section className="sm:grid grid-cols-2 w-5/6 gap-3 mx-auto">
        {fourPosts.map((post: MetadataProps) => (
          <div key={post.title}>
            <SinglePost
              title={post.title}
              description={post.description}
              date={post.date}
              slug={post.slug}
              tags={post.tags}
              isPaginationPage={true}
            />
          </div>
        ))}
      </section>
    </div>
  )
}

export default BlogPageList
