import { Inter } from 'next/font/google'
import { MetadataProps, getAllPosts } from '@/lib/notionAPI'
import Head from 'next/head'
import { SinglePost } from '@/components/Post/SinglePost'

export async function getStaticProps<GetStaticProps>(context: any) {
  const allPosts: MetadataProps[] = await getAllPosts()
  return {
    props: { allPosts },
    revalidate: 60, // 60秒ごと更新する(ISR)
  }
}
type Props = {
  allPosts: MetadataProps[]
}

export default function Home({ allPosts }: Props) {
  console.log(allPosts)
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          Notion Blog🚀
        </h1>
      </main>
      {allPosts.map((post: any) => (
        <div className="mx-4" key={post.title}>
          <SinglePost
            title={post.title}
            description={post.description}
            date={post.date}
            slug={post.slug}
            tags={post.tags}
          />
        </div>
      ))}
    </div>
  )
}
